# Site settings
title: Soar Valley MDC
header-img: img/home-bg.jpg
email: soarvalleymdc@gmail.com
copyright_name: Soar Valley Metal Detecting Club
description: "Welcome to the Home page of the Soar Valley Metal Detecting Club"
baseurl: "/soarvalley-mdc" #this will need to change once it's hosted on it's own domain
url: "http://soarvalleymdc.org.uk"
twitter_username: 
github_username:  
facebook_username: 
email_username: soarvalleymdc@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "news/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
