# Site settings
title: Soar Valley MDC
header-img: img/home-bg.jpg
email: bryan@know-how.com
copyright_name: Your/Project/Corporate Name
description: "Welcome to the Home page of the Soar Valley Metal Detecting Club"
baseurl: "/soarvalley-mdc"
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
email_username:  your-email@yourdomain.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
