# Site settings
title: Soar Valley MDC
header-img: img/home-bg.jpg
email: bryan@know-how.com
copyright_name: Soar Valley Metal Detecting Club
description: "Welcome to the Home page of the Soar Valley Metal Detecting Club"
baseurl: "/soarvalley-mdc"
url: "http://soarvalleymdc.org.uk"
twitter_username: 
github_username:  
facebook_username: 
email_username:  bryan@know-how.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "news/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
